// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Ulisses de frente":return img`
....................
........eeeee.......
........eddde.......
........dfdfd.......
........ddddd.......
........ddfdd.......
......dd9ddd9dd.....
......dd99999dd.....
......dd99999dd.....
......dd99999dd.....
......dd99999dd.....
......dd99999dd.....
......dd99999dd.....
........99999.......
........99999.......
........99999.......
........dd.dd.......
........dd.dd.......
........dd.dd.......
........dd.dd.......
`;
            case "image2":
            case "Uliisses do lado esquerdo":return img`
....................
.......eeeee........
.......ddeee........
.......fddee........
.......dddde........
.......fddde........
........99dd........
........99dd........
........99dd........
........99dd........
........99dd........
........99dd........
........99dd........
........9999........
........9999........
........9999........
..........dd........
..........dd........
..........dd........
.........ddd........
`;
            case "image3":
            case "Ulisses do lado direito":return img`
....................
.........eeeee......
.........eeedd......
.........eeddf......
.........edddd......
.........edddf......
.........dd99.......
.........dd99.......
.........dd99.......
.........dd99.......
.........dd99.......
.........dd99.......
.........dd99.......
.........dd99.......
.........9999.......
.........9999.......
.........dd.........
.........dd.........
.........dd.........
.........ddd........
`;
            case "image5":
            case "Companheiro 2 - Direito":return img`
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
...................3
....................
....................
....................
....................
....................
....................
`;
            case "image4":
            case "Companheiro 2 - frente":return img`
....................
....................
....................
....................
....................
.....5555555555.....
....222222222222....
...55555555555555...
....feeeeeeeeeef....
....feddddddddef....
....fddbfddfbddf....
....fdd1fddf1ddf....
....ffddddddddff....
.....fdddffdddf.....
....ddf222222fdd....
....ddf222222fdd....
....ddfee55eefdd....
.......ffffff.......
.......ff..ff.......
.......ff..ff.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("json", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
